spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/zhuyi
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
management:
  security:
    enabled: false

mybatis:
    configuration:
      map-underscore-to-camel-case: true


