spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/zhuyi
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      host: localhost
      port: 6379
      database: 0
      pool:
        max-active: 300
        max-wait: 10000
        max-idle: 100
        min-idle: 8
      timeout: 0
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
  devtools:
    restart:
      enabled: true
management:
  security:
    enabled: false

mybatis:
    configuration:
      map-underscore-to-camel-case: true


